#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v26
# autospec commit: 99a7985
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kolourpaint
Version  : 25.04.1
Release  : 80
URL      : https://download.kde.org/stable/release-service/25.04.1/src/kolourpaint-25.04.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/25.04.1/src/kolourpaint-25.04.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/25.04.1/src/kolourpaint-25.04.1.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause BSD-3-Clause CC0-1.0 GFDL-1.2 GPL-2.0 LGPL-2.0 LGPL-2.1 LGPL-3.0
Requires: kolourpaint-bin = %{version}-%{release}
Requires: kolourpaint-data = %{version}-%{release}
Requires: kolourpaint-lib = %{version}-%{release}
Requires: kolourpaint-license = %{version}-%{release}
Requires: kolourpaint-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kcrash-dev
BuildRequires : ki18n-dev
BuildRequires : kio-dev
BuildRequires : kjobwidgets-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
http://www.kolourpaint.org/
For licensing and warranty information, read COPYING.
For known problems with this release of KolourPaint, read BUGS.
For what changes have been made, read NEWS.
For developer information, checkout branches/kolourpaint/control/.

%package bin
Summary: bin components for the kolourpaint package.
Group: Binaries
Requires: kolourpaint-data = %{version}-%{release}
Requires: kolourpaint-license = %{version}-%{release}

%description bin
bin components for the kolourpaint package.


%package data
Summary: data components for the kolourpaint package.
Group: Data

%description data
data components for the kolourpaint package.


%package dev
Summary: dev components for the kolourpaint package.
Group: Development
Requires: kolourpaint-lib = %{version}-%{release}
Requires: kolourpaint-bin = %{version}-%{release}
Requires: kolourpaint-data = %{version}-%{release}
Provides: kolourpaint-devel = %{version}-%{release}
Requires: kolourpaint = %{version}-%{release}

%description dev
dev components for the kolourpaint package.


%package doc
Summary: doc components for the kolourpaint package.
Group: Documentation

%description doc
doc components for the kolourpaint package.


%package lib
Summary: lib components for the kolourpaint package.
Group: Libraries
Requires: kolourpaint-data = %{version}-%{release}
Requires: kolourpaint-license = %{version}-%{release}

%description lib
lib components for the kolourpaint package.


%package license
Summary: license components for the kolourpaint package.
Group: Default

%description license
license components for the kolourpaint package.


%package locales
Summary: locales components for the kolourpaint package.
Group: Default

%description locales
locales components for the kolourpaint package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kolourpaint-25.04.1
cd %{_builddir}/kolourpaint-25.04.1
pushd ..
cp -a kolourpaint-25.04.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1747103959
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DQT_MAJOR_VERSION=6  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1747103959
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kolourpaint
cp %{_builddir}/kolourpaint-%{version}/COPYING %{buildroot}/usr/share/package-licenses/kolourpaint/16f2f17f30faa850073c3ca39c4fbff4c53c3e71 || :
cp %{_builddir}/kolourpaint-%{version}/COPYING.DOC %{buildroot}/usr/share/package-licenses/kolourpaint/1bd373e4851a93027ba70064bd7dbdc6827147e1 || :
cp %{_builddir}/kolourpaint-%{version}/COPYING.LIB %{buildroot}/usr/share/package-licenses/kolourpaint/c08668a6ace9b36ba46940609040748161b03a37 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/BSD-2-Clause.txt %{buildroot}/usr/share/package-licenses/kolourpaint/52039e5c19c950d4c7d6ec5da42ebba2c6def7ee || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kolourpaint/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kolourpaint/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kolourpaint/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/LGPL-2.1-only.txt %{buildroot}/usr/share/package-licenses/kolourpaint/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/LGPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kolourpaint/19d98e1b6f8ef12849ea4012a052d3907f336c91 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kolourpaint/e458941548e0864907e654fa2e192844ae90fc32 || :
cp %{_builddir}/kolourpaint-%{version}/LICENSES/LicenseRef-KDE-Accepted-LGPL.txt %{buildroot}/usr/share/package-licenses/kolourpaint/e458941548e0864907e654fa2e192844ae90fc32 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kolourpaint
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kolourpaint
/usr/bin/kolourpaint

%files data
%defattr(-,root,root,-)
/usr/share/applications/org.kde.kolourpaint.desktop
/usr/share/icons/hicolor/128x128/apps/kolourpaint.png
/usr/share/icons/hicolor/16x16/apps/kolourpaint.png
/usr/share/icons/hicolor/22x22/apps/kolourpaint.png
/usr/share/icons/hicolor/32x32/apps/kolourpaint.png
/usr/share/icons/hicolor/48x48/apps/kolourpaint.png
/usr/share/icons/hicolor/scalable/apps/kolourpaint.svgz
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_brush.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_color_eraser.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_color_picker.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_curve.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_ellipse.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_elliptical_selection.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_eraser.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_flood_fill.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_free_form_selection.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_line.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_pen.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_polygon.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_polyline.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_rect_selection.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_rectangle.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_rounded_rectangle.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_spraycan.png
/usr/share/kolourpaint/icons/hicolor/16x16/actions/tool_text.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_brush.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_color_eraser.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_color_picker.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_curve.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_ellipse.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_elliptical_selection.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_eraser.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_flood_fill.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_free_form_selection.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_line.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_pen.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_polygon.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_polyline.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_rect_selection.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_rectangle.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_rounded_rectangle.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_spraycan.png
/usr/share/kolourpaint/icons/hicolor/22x22/actions/tool_text.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_brush.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_color_eraser.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_color_picker.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_curve.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_ellipse.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_elliptical_selection.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_eraser.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_flood_fill.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_free_form_selection.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_line.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_pen.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_polygon.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_polyline.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_rect_selection.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_rectangle.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_rounded_rectangle.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_spraycan.png
/usr/share/kolourpaint/icons/hicolor/32x32/actions/tool_text.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_brush.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_color_eraser.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_color_picker.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_curve.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_ellipse.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_elliptical_selection.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_eraser.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_flood_fill.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_free_form_selection.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_line.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_pen.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_polygon.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_polyline.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_rect_selection.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_rectangle.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_rounded_rectangle.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_spraycan.png
/usr/share/kolourpaint/icons/hicolor/48x48/actions/tool_text.png
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_brush.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_color_eraser.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_color_picker.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_curve.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_ellipse.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_elliptical_selection.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_eraser.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_flood_fill.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_free_form_selection.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_line.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_pen.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_polygon.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_polyline.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_rect_selection.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_rectangle.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_rounded_rectangle.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_spraycan.svgz
/usr/share/kolourpaint/icons/hicolor/scalable/actions/tool_text.svgz
/usr/share/metainfo/org.kde.kolourpaint.appdata.xml

%files dev
%defattr(-,root,root,-)
/usr/lib64/libkolourpaint_lgpl.so

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/ca/kolourpaint/image_balance.png
/usr/share/doc/HTML/ca/kolourpaint/image_emboss.png
/usr/share/doc/HTML/ca/kolourpaint/image_flatten.png
/usr/share/doc/HTML/ca/kolourpaint/image_invert.png
/usr/share/doc/HTML/ca/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/ca/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/ca/kolourpaint/image_rotate.png
/usr/share/doc/HTML/ca/kolourpaint/image_skew.png
/usr/share/doc/HTML/ca/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/ca/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/ca/kolourpaint/index.docbook
/usr/share/doc/HTML/de/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/de/kolourpaint/image_balance.png
/usr/share/doc/HTML/de/kolourpaint/image_emboss.png
/usr/share/doc/HTML/de/kolourpaint/image_flatten.png
/usr/share/doc/HTML/de/kolourpaint/image_flip.png
/usr/share/doc/HTML/de/kolourpaint/image_invert.png
/usr/share/doc/HTML/de/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/de/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/de/kolourpaint/image_rotate.png
/usr/share/doc/HTML/de/kolourpaint/image_skew.png
/usr/share/doc/HTML/de/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/de/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/de/kolourpaint/index.docbook
/usr/share/doc/HTML/en/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/en/kolourpaint/brush_shapes.png
/usr/share/doc/HTML/en/kolourpaint/color_box.png
/usr/share/doc/HTML/en/kolourpaint/eraser_shapes.png
/usr/share/doc/HTML/en/kolourpaint/fcc_std_text.png
/usr/share/doc/HTML/en/kolourpaint/fcc_trans_text.png
/usr/share/doc/HTML/en/kolourpaint/fill_color_similarity.png
/usr/share/doc/HTML/en/kolourpaint/fill_style.png
/usr/share/doc/HTML/en/kolourpaint/image_balance.png
/usr/share/doc/HTML/en/kolourpaint/image_emboss.png
/usr/share/doc/HTML/en/kolourpaint/image_flatten.png
/usr/share/doc/HTML/en/kolourpaint/image_invert.png
/usr/share/doc/HTML/en/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/en/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/en/kolourpaint/image_rotate.png
/usr/share/doc/HTML/en/kolourpaint/image_skew.png
/usr/share/doc/HTML/en/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/en/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/en/kolourpaint/index.docbook
/usr/share/doc/HTML/en/kolourpaint/line_width.png
/usr/share/doc/HTML/en/kolourpaint/lines_30_45_deg.png
/usr/share/doc/HTML/en/kolourpaint/lines_30_deg.png
/usr/share/doc/HTML/en/kolourpaint/lines_45_deg.png
/usr/share/doc/HTML/en/kolourpaint/rotate_image_30.png
/usr/share/doc/HTML/en/kolourpaint/rotate_selection_30.png
/usr/share/doc/HTML/en/kolourpaint/screenshot_acquiring.png
/usr/share/doc/HTML/en/kolourpaint/selections_opaque_transparent.png
/usr/share/doc/HTML/en/kolourpaint/spraycan_patterns.png
/usr/share/doc/HTML/en/kolourpaint/text_zoom_grid.png
/usr/share/doc/HTML/en/kolourpaint/tool_brush.png
/usr/share/doc/HTML/en/kolourpaint/tool_color_picker.png
/usr/share/doc/HTML/en/kolourpaint/tool_color_washer.png
/usr/share/doc/HTML/en/kolourpaint/tool_curve.png
/usr/share/doc/HTML/en/kolourpaint/tool_ellipse.png
/usr/share/doc/HTML/en/kolourpaint/tool_elliptical_selection.png
/usr/share/doc/HTML/en/kolourpaint/tool_eraser.png
/usr/share/doc/HTML/en/kolourpaint/tool_flood_fill.png
/usr/share/doc/HTML/en/kolourpaint/tool_free_form_selection.png
/usr/share/doc/HTML/en/kolourpaint/tool_line.png
/usr/share/doc/HTML/en/kolourpaint/tool_pen.png
/usr/share/doc/HTML/en/kolourpaint/tool_polygon.png
/usr/share/doc/HTML/en/kolourpaint/tool_polyline.png
/usr/share/doc/HTML/en/kolourpaint/tool_polystar.png
/usr/share/doc/HTML/en/kolourpaint/tool_rect_selection.png
/usr/share/doc/HTML/en/kolourpaint/tool_rectangle.png
/usr/share/doc/HTML/en/kolourpaint/tool_rectangles.png
/usr/share/doc/HTML/en/kolourpaint/tool_rounded_rectangle.png
/usr/share/doc/HTML/en/kolourpaint/tool_selections.png
/usr/share/doc/HTML/en/kolourpaint/tool_spraycan.png
/usr/share/doc/HTML/en/kolourpaint/tool_text.png
/usr/share/doc/HTML/en/kolourpaint/tool_zoom.png
/usr/share/doc/HTML/en/kolourpaint/view_thumbnails.png
/usr/share/doc/HTML/es/kolourpaint/brush_shapes.png
/usr/share/doc/HTML/es/kolourpaint/color_box.png
/usr/share/doc/HTML/es/kolourpaint/eraser_shapes.png
/usr/share/doc/HTML/es/kolourpaint/fcc_std_text.png
/usr/share/doc/HTML/es/kolourpaint/fcc_trans_text.png
/usr/share/doc/HTML/es/kolourpaint/fill_color_similarity.png
/usr/share/doc/HTML/es/kolourpaint/fill_style.png
/usr/share/doc/HTML/es/kolourpaint/image_balance.png
/usr/share/doc/HTML/es/kolourpaint/image_emboss.png
/usr/share/doc/HTML/es/kolourpaint/image_flatten.png
/usr/share/doc/HTML/es/kolourpaint/image_invert.png
/usr/share/doc/HTML/es/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/es/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/es/kolourpaint/image_rotate.png
/usr/share/doc/HTML/es/kolourpaint/image_skew.png
/usr/share/doc/HTML/es/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/es/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/es/kolourpaint/index.docbook
/usr/share/doc/HTML/es/kolourpaint/line_width.png
/usr/share/doc/HTML/es/kolourpaint/lines_30_45_deg.png
/usr/share/doc/HTML/es/kolourpaint/lines_30_deg.png
/usr/share/doc/HTML/es/kolourpaint/lines_45_deg.png
/usr/share/doc/HTML/es/kolourpaint/rotate_image_30.png
/usr/share/doc/HTML/es/kolourpaint/rotate_selection_30.png
/usr/share/doc/HTML/es/kolourpaint/selections_opaque_transparent.png
/usr/share/doc/HTML/es/kolourpaint/spraycan_patterns.png
/usr/share/doc/HTML/es/kolourpaint/text_zoom_grid.png
/usr/share/doc/HTML/es/kolourpaint/tool_brush.png
/usr/share/doc/HTML/es/kolourpaint/tool_color_picker.png
/usr/share/doc/HTML/es/kolourpaint/tool_color_washer.png
/usr/share/doc/HTML/es/kolourpaint/tool_curve.png
/usr/share/doc/HTML/es/kolourpaint/tool_ellipse.png
/usr/share/doc/HTML/es/kolourpaint/tool_elliptical_selection.png
/usr/share/doc/HTML/es/kolourpaint/tool_eraser.png
/usr/share/doc/HTML/es/kolourpaint/tool_flood_fill.png
/usr/share/doc/HTML/es/kolourpaint/tool_free_form_selection.png
/usr/share/doc/HTML/es/kolourpaint/tool_line.png
/usr/share/doc/HTML/es/kolourpaint/tool_pen.png
/usr/share/doc/HTML/es/kolourpaint/tool_polygon.png
/usr/share/doc/HTML/es/kolourpaint/tool_polyline.png
/usr/share/doc/HTML/es/kolourpaint/tool_polystar.png
/usr/share/doc/HTML/es/kolourpaint/tool_rect_selection.png
/usr/share/doc/HTML/es/kolourpaint/tool_rectangle.png
/usr/share/doc/HTML/es/kolourpaint/tool_rectangles.png
/usr/share/doc/HTML/es/kolourpaint/tool_rounded_rectangle.png
/usr/share/doc/HTML/es/kolourpaint/tool_selections.png
/usr/share/doc/HTML/es/kolourpaint/tool_spraycan.png
/usr/share/doc/HTML/es/kolourpaint/tool_text.png
/usr/share/doc/HTML/es/kolourpaint/view_thumbnails.png
/usr/share/doc/HTML/et/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/et/kolourpaint/index.docbook
/usr/share/doc/HTML/fr/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/fr/kolourpaint/index.docbook
/usr/share/doc/HTML/gl/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/gl/kolourpaint/index.docbook
/usr/share/doc/HTML/it/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/it/kolourpaint/index.docbook
/usr/share/doc/HTML/nl/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/nl/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/nl/kolourpaint/index.docbook
/usr/share/doc/HTML/pl/kolourpaint/fullscreen_mode.png
/usr/share/doc/HTML/pl/kolourpaint/image_balance.png
/usr/share/doc/HTML/pl/kolourpaint/image_emboss.png
/usr/share/doc/HTML/pl/kolourpaint/image_flatten.png
/usr/share/doc/HTML/pl/kolourpaint/image_flip.png
/usr/share/doc/HTML/pl/kolourpaint/image_invert.png
/usr/share/doc/HTML/pl/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/pl/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/pl/kolourpaint/image_rotate.png
/usr/share/doc/HTML/pl/kolourpaint/image_skew.png
/usr/share/doc/HTML/pl/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/pl/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/pl/kolourpaint/index.docbook
/usr/share/doc/HTML/pt/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/pt/kolourpaint/index.docbook
/usr/share/doc/HTML/pt_BR/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/pt_BR/kolourpaint/brush_shapes.png
/usr/share/doc/HTML/pt_BR/kolourpaint/color_box.png
/usr/share/doc/HTML/pt_BR/kolourpaint/eraser_shapes.png
/usr/share/doc/HTML/pt_BR/kolourpaint/fcc_std_text.png
/usr/share/doc/HTML/pt_BR/kolourpaint/fcc_trans_text.png
/usr/share/doc/HTML/pt_BR/kolourpaint/fill_color_similarity.png
/usr/share/doc/HTML/pt_BR/kolourpaint/fill_style.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_balance.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_emboss.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_flatten.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_invert.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_rotate.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_skew.png
/usr/share/doc/HTML/pt_BR/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/pt_BR/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kolourpaint/index.docbook
/usr/share/doc/HTML/pt_BR/kolourpaint/line_width.png
/usr/share/doc/HTML/pt_BR/kolourpaint/lines_30_45_deg.png
/usr/share/doc/HTML/pt_BR/kolourpaint/lines_30_deg.png
/usr/share/doc/HTML/pt_BR/kolourpaint/lines_45_deg.png
/usr/share/doc/HTML/pt_BR/kolourpaint/rotate_image_30.png
/usr/share/doc/HTML/pt_BR/kolourpaint/rotate_selection_30.png
/usr/share/doc/HTML/pt_BR/kolourpaint/screenshot_acquiring.png
/usr/share/doc/HTML/pt_BR/kolourpaint/selections_opaque_transparent.png
/usr/share/doc/HTML/pt_BR/kolourpaint/spraycan_patterns.png
/usr/share/doc/HTML/pt_BR/kolourpaint/text_zoom_grid.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_brush.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_color_picker.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_color_washer.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_curve.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_ellipse.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_elliptical_selection.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_eraser.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_flood_fill.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_free_form_selection.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_line.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_pen.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_polygon.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_polyline.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_polystar.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_rect_selection.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_rectangle.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_rectangles.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_rounded_rectangle.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_selections.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_spraycan.png
/usr/share/doc/HTML/pt_BR/kolourpaint/tool_text.png
/usr/share/doc/HTML/pt_BR/kolourpaint/view_thumbnails.png
/usr/share/doc/HTML/ru/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/ru/kolourpaint/image_balance.png
/usr/share/doc/HTML/ru/kolourpaint/image_emboss.png
/usr/share/doc/HTML/ru/kolourpaint/image_flatten.png
/usr/share/doc/HTML/ru/kolourpaint/image_invert.png
/usr/share/doc/HTML/ru/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/ru/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/ru/kolourpaint/image_rotate.png
/usr/share/doc/HTML/ru/kolourpaint/image_skew.png
/usr/share/doc/HTML/ru/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/ru/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/ru/kolourpaint/index.docbook
/usr/share/doc/HTML/ru/kolourpaint/screenshot_acquiring.png
/usr/share/doc/HTML/ru/kolourpaint/view_thumbnails.png
/usr/share/doc/HTML/sl/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/sl/kolourpaint/index.docbook
/usr/share/doc/HTML/sv/kolourpaint/image_balance.png
/usr/share/doc/HTML/sv/kolourpaint/image_emboss.png
/usr/share/doc/HTML/sv/kolourpaint/image_flatten.png
/usr/share/doc/HTML/sv/kolourpaint/image_flip.png
/usr/share/doc/HTML/sv/kolourpaint/image_invert.png
/usr/share/doc/HTML/sv/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/sv/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/sv/kolourpaint/image_rotate.png
/usr/share/doc/HTML/sv/kolourpaint/image_skew.png
/usr/share/doc/HTML/sv/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/sv/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/sv/kolourpaint/index.docbook
/usr/share/doc/HTML/sv/kolourpaint/view_thumbnails.png
/usr/share/doc/HTML/uk/kolourpaint/KolourPaint.png
/usr/share/doc/HTML/uk/kolourpaint/image_balance.png
/usr/share/doc/HTML/uk/kolourpaint/image_emboss.png
/usr/share/doc/HTML/uk/kolourpaint/image_flatten.png
/usr/share/doc/HTML/uk/kolourpaint/image_invert.png
/usr/share/doc/HTML/uk/kolourpaint/image_reduce_colors.png
/usr/share/doc/HTML/uk/kolourpaint/image_resize_scale.png
/usr/share/doc/HTML/uk/kolourpaint/image_rotate.png
/usr/share/doc/HTML/uk/kolourpaint/image_skew.png
/usr/share/doc/HTML/uk/kolourpaint/image_soften_sharpen.png
/usr/share/doc/HTML/uk/kolourpaint/index.cache.bz2
/usr/share/doc/HTML/uk/kolourpaint/index.docbook
/usr/share/doc/HTML/uk/kolourpaint/screenshot_acquiring.png

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libkolourpaint_lgpl.so.5
/usr/lib64/libkolourpaint_lgpl.so.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kolourpaint/16f2f17f30faa850073c3ca39c4fbff4c53c3e71
/usr/share/package-licenses/kolourpaint/19d98e1b6f8ef12849ea4012a052d3907f336c91
/usr/share/package-licenses/kolourpaint/1bd373e4851a93027ba70064bd7dbdc6827147e1
/usr/share/package-licenses/kolourpaint/52039e5c19c950d4c7d6ec5da42ebba2c6def7ee
/usr/share/package-licenses/kolourpaint/81b58c89ceef8e9f8bd5d00a287edbd15f9d3567
/usr/share/package-licenses/kolourpaint/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kolourpaint/a4c60b3fefda228cd7439d3565df043192fef137
/usr/share/package-licenses/kolourpaint/c08668a6ace9b36ba46940609040748161b03a37
/usr/share/package-licenses/kolourpaint/e458941548e0864907e654fa2e192844ae90fc32

%files locales -f kolourpaint.lang
%defattr(-,root,root,-)

